import React from 'react';
import {ArrowRight,Compass,Layers3,LineChart,Workflow} from 'lucide-react';
import {Link} from 'react-router-dom';

export default function About(){
 const strengths=[{Icon:Workflow,title:'Operational depth',text:'20+ years across logistics, warehousing, distribution, container operations and supply-chain execution.'},{Icon:LineChart,title:'Analytical leverage',text:'Using data and business intelligence to reveal patterns, bottlenecks and warning signals that conventional reporting can miss.'},{Icon:Layers3,title:'Systems thinking',text:'Connecting people, process, measurements and context instead of treating KPIs as isolated numbers.'},{Icon:Compass,title:'Builder mindset',text:'Turning hypotheses into dashboards, experiments, prototypes and inspectable public evidence.'}];
 return <div className="bg-[#050807] min-h-screen pt-32 pb-24 text-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div className="max-w-5xl"><div className="eyebrow">The operator behind the systems</div><h1 className="mt-5 text-5xl sm:text-7xl font-black tracking-[-0.055em] leading-[.92] text-white">Experience on the floor.<br/><span className="text-gradient">Intelligence above it.</span></h1><p className="mt-8 max-w-3xl text-xl leading-relaxed text-slate-400">I am Lam Teck Sing Andrew. My foundation is not theory: it is more than two decades of operational work. Today I combine that experience with analytics, data and AI to build better ways of seeing risk, understanding systems and acting earlier.</p></div>
  <div className="mt-20 grid md:grid-cols-2 gap-4">{strengths.map(({Icon,title,text})=><div key={title} className="system-card rounded-3xl p-8"><Icon className="w-7 h-7 text-emerald-300"/><h2 className="mt-10 text-2xl font-black text-white">{title}</h2><p className="mt-3 text-slate-400 leading-relaxed">{text}</p></div>)}</div>
  <div className="mt-24 grid lg:grid-cols-[.7fr_1.3fr] gap-10 border-t border-white/[0.08] pt-16"><div><div className="eyebrow">Operating philosophy</div><h2 className="mt-4 text-3xl font-black text-white">Technology earns its place through better decisions.</h2></div><div className="space-y-6 text-lg leading-relaxed text-slate-400"><p>I start with how work actually happens. Then I ask where information arrives too late, where assumptions hide, where signals disagree and where a better model could change an operational decision.</p><p>I separate evidence from demonstration. Anonymised operating data is labelled as such. Synthetic experiments are labelled as synthetic. A prototype is not described as a product, and an inference is not presented as certainty.</p><p>The goal is not more dashboards or more AI. The goal is earlier understanding, better execution and measurable action.</p></div></div>
  <div className="mt-24 rounded-[2rem] border border-white/[0.08] bg-white/[0.025] p-8 sm:p-12 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-8"><div><div className="eyebrow">Evidence before claims</div><h3 className="mt-3 text-2xl font-black text-white">See the work, not just the biography.</h3></div><Link to="/insights" className="premium-button rounded-full px-6 py-3.5 font-bold inline-flex items-center gap-2">Explore evidence <ArrowRight className="w-4 h-4"/></Link></div>
 </div></div>
}