import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Clock,ExternalLink,FlaskConical,Search} from 'lucide-react';
import {createClient} from '@sanity/client';
const client=createClient({projectId:'h3pl1rfx',dataset:'production',useCdn:true,apiVersion:'2024-01-01'});
const flagship=[
 {title:'Container Operations Evidence',tag:'REAL OPERATING EVIDENCE',text:'Anonymised Maxwell Excel records covering 391 container jobs across seven reporting periods. Dataset figures are factual; no unverified profit, savings or production-impact claim is made.',to:'/maxwell-excel'},
 {title:'VELYQUA 维澜',tag:'E2 PRODUCT · E0/E1 PHYSICAL HYPOTHESIS',text:'A live freshwater operating-system prototype plus a governed experiment asking whether low-cost continuous signals can provide useful earlier warning. The physical hypothesis is not yet scientifically validated.',to:'/velyqua'},
 {title:'Multi-Signal Risk Simulator',tag:'E1 SYNTHETIC DEMONSTRATION',text:'An inspectable weighted-rule environment for exploring how multiple signals can combine. It is not presented as a trained or validated predictive model.',to:'/demo'}
];
const controlledExcerpts={
 'the-hidden-cost-of-inefficient-warehouse-logistics':'Experience-based operational ranges from anonymised career records. The ranges are not independently audited benchmarks and should be read as evidence requiring source support.',
 'supply-chain-control-tower-early-warning-system':'AI-assisted synthetic demonstration of a weighted-rule early-warning method. The 24-day result comes from an engineered scenario, not a trained predictive model or measured production outcome.',
 'cold-chain-risk-intelligence-and-performance-analytics':'AI-assisted synthetic demonstration using 1,800 generated records across six warehouse zones. It illustrates analysis and decision-support design, not employer deployment or measured production impact.'
};
export default function Insights(){const [articles,setArticles]=useState([]),[loading,setLoading]=useState(true),[q,setQ]=useState('');useEffect(()=>{client.fetch(`*[_type == "post" && !(_id in path("drafts.**"))] | order(publishedAt desc){_id,title,"slug":slug.current,category,publishedAt,readTime,excerpt}`).then(x=>{setArticles((x||[]).map(a=>({...a,excerpt:controlledExcerpts[a.slug]||a.excerpt})));setLoading(false)}).catch(()=>setLoading(false))},[]);const filtered=articles.filter(a=>(a.title||'').toLowerCase().includes(q.toLowerCase())||(a.excerpt||'').toLowerCase().includes(q.toLowerCase()));return <div className="bg-[#050807] min-h-screen pt-32 pb-24 text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
 <div className="max-w-4xl"><div className="eyebrow">Evidence hub</div><h1 className="mt-5 text-5xl sm:text-7xl font-black tracking-[-0.055em] leading-[.92]">Claims are easy.<br/><span className="text-gradient">Evidence compounds.</span></h1><p className="mt-7 max-w-3xl text-lg text-slate-400 leading-relaxed">Projects, operating analyses and experiments connecting frontline experience with analytics, systems thinking and AI. Evidence types and maturity are identified rather than blurred together.</p></div>
 <div className="mt-16 grid lg:grid-cols-3 gap-4">{flagship.map(p=>{const body=<><div className="flex justify-between gap-4"><FlaskConical className="w-6 h-6 text-emerald-300 shrink-0"/><span className="text-[9px] leading-relaxed text-right font-bold tracking-[.12em] text-amber-300">{p.tag}</span></div><h2 className="mt-12 text-2xl font-black">{p.title}</h2><p className="mt-3 min-h-[120px] text-slate-400 leading-relaxed">{p.text}</p><div className="mt-6 text-sm font-bold text-emerald-300 inline-flex gap-2 items-center">Inspect evidence {p.href?<ExternalLink className="w-4 h-4"/>:<ArrowRight className="w-4 h-4"/>}</div></>;return p.href?<a key={p.title} href={p.href} target="_blank" rel="noreferrer" className="system-card rounded-3xl p-7">{body}</a>:<Link key={p.title} to={p.to} className="system-card rounded-3xl p-7">{body}</Link>})}</div>
 <div className="mt-24 flex flex-col md:flex-row md:items-end justify-between gap-6 border-t border-white/[0.08] pt-14"><div><div className="eyebrow">Published thinking</div><h2 className="mt-3 text-3xl font-black">Field notes & case studies</h2></div><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500"/><label htmlFor="evidence-search" className="sr-only">Search evidence</label><input id="evidence-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search evidence..." className="w-full md:w-72 rounded-full border border-white/[0.1] bg-white/[0.025] py-3 pl-11 pr-5 text-sm outline-none focus:border-emerald-300/40"/></div></div>
 <div className="mt-8">{loading?<div className="text-slate-500 py-10">Loading evidence…</div>:filtered.length===0?<div className="rounded-3xl border border-white/[0.07] bg-white/[0.02] p-10 text-slate-400">No matching published articles yet. The flagship evidence above remains available for inspection.</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map(a=><article key={a._id} className="system-card rounded-3xl p-7 flex flex-col"><div className="flex justify-between gap-3 text-[10px] tracking-wider uppercase"><span className="text-emerald-300">{a.category||'Insight'}</span><span className="text-slate-600 inline-flex items-center gap-1"><Clock className="w-3 h-3"/>{a.readTime||'5 min'}</span></div><h3 className="mt-8 text-xl font-black">{a.title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-400 flex-1">{a.excerpt}</p><Link to={`/insights/${a.slug}`} className="mt-7 text-sm font-bold text-amber-300 inline-flex gap-2 items-center">Read evidence <ArrowRight className="w-4 h-4"/></Link></article>)}</div>}</div>
 </div></div>}
